### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by bonald** [newtondev/no-dev-fee-stratum-proxy#1]
x                                                                     xx nodevfee > SyntaxError: Unexpected token { in JSON at position 166                                                                                                x
x                                                                     xx nodevfee >     at JSON.parse (<anonymous>)                                                                                                                        x
x                                                                     xx nodevfee >     at Socket.localsocket.on (/root/no-dev-fee-stratum-proxy/server.js:40:30)                                                                          x
x                                                                     xx nodevfee >     at emitOne (events.js:116:13)                                                                                                                      x
x                                                                     xx nodevfee >     at Socket.emit (events.js:211:7)                                                                                                                   x
x                                                                     xx nodevfee >     at addChunk (_stream_readable.js:263:12)                                                                                                           x
x                                                                     xx nodevfee >     at readableAddChunk (_stream_readable.js:250:11)                                                                                                   x
x                                                                     xx nodevfee >     at Socket.Readable.push (_stream_readable.js:208:10)                                                                                               x
x                                                                     xx nodevfee >     at TCP.onread (net.js:594:20)                                                                                                                      x
x                                                                     xx nodevfee > { SyntaxError: Unexpected token { in JSON at position 166                                                                                              x
x                                                                     xx nodevfee >     at JSON.parse (<anonymous>)                                                                                                                        x
x                                                                     xx nodevfee >     at Socket.localsocket.on (/root/no-dev-fee-stratum-proxy/server.js:40:30)                                                                          x
x                                                                     xx nodevfee >     at emitOne (events.js:116:13)                                                                                                                      x
x                                                                     xx nodevfee >     at Socket.emit (events.js:211:7)                                                                                                                   x
x                                                                     xx nodevfee >     at addChunk (_stream_readable.js:263:12)                                                                                                           x
x                                                                     xx nodevfee >     at readableAddChunk (_stream_readable.js:250:11)                                                                                                   x
x                                                                     xx nodevfee >     at Socket.Readable.push (_stream_readable.js:208:10)                                                                                               x
x                                                                     xx nodevfee >     at TCP.onread (net.js:594:20)                                                                                                                      x
x                                                                     xx nodevfee >   stackframes:                                                                                                                                         x
x                                                                     xx nodevfee >    [ { file_name: null, line_number: null },                                                                                                           x
x                                                                     xx nodevfee >      { file_name: '/root/no-dev-fee-stratum-proxy/server.js',                                                                                          x
x                                                                     xx nodevfee >        line_number: 40 },                                                                                                                              x
x                                                                     xx nodevfee >      { file_name: 'events.js', line_number: 116 },                                                                                                     x
x                                                                     xx nodevfee >      { file_name: 'events.js', line_number: 211 },                                                                                                     x
x                                                                     xx nodevfee >      { file_name: '_stream_readable.js', line_number: 263 },                                                                                           x
x                                                                     xx nodevfee >      { file_name: '_stream_readable.js', line_number: 250 },                                                                                           x
x                                                                     xx nodevfee >      { file_name: '_stream_readable.js', line_number: 208 },                                                                                           x
x                                                                     xx nodevfee >      { file_name: 'net.js', line_number: 594 } ] }                                                                                                     x

**Comment by newtondev** [comment]
Thanks for posting. Can you please provide me with the raw text that was read just before the JSON.parse() line, thanks.

**Comment by bonald** [comment]
I had some console.log commented in your script, so it's missing from the log file.
I'll uncomment the code and try again.

That was on ethermine pool. You got it working on what pool ?
