### ISSUE TITLE
Error: check your arguments and try again!

### ISSUE THREAD

**Issue by NikiKaCode** [newtondev/no-dev-fee-stratum-proxy#2]
hi , when start scrypt  i get this error :

> newtondev-no-dev-fee-stratum-proxy@1.0.0 start D:\mining\pr1\no-dev-fee-stratum-proxy-master
> node server.js

Error: check your arguments and try again!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! newtondev-no-dev-fee-stratum-proxy@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the newtondev-no-dev-fee-stratum-proxy@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Fatality\AppData\Roaming\npm-cache\_logs\2018-03-23T19_26_01_905Z-debug.log

log file : 
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Fatality\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.7.1
3 info using node@v9.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle newtondev-no-dev-fee-stratum-proxy@1.0.0~prestart: newtondev-no-dev-fee-stratum-proxy@1.0.0
6 info lifecycle newtondev-no-dev-fee-stratum-proxy@1.0.0~start: newtondev-no-dev-fee-stratum-proxy@1.0.0
7 verbose lifecycle newtondev-no-dev-fee-stratum-proxy@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle newtondev-no-dev-fee-stratum-proxy@1.0.0~start: PATH: C:\Users\Fatality\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\mining\pr1\no-dev-fee-stratum-proxy-master\node_modules\.bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\libnvvp;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PowerShell\6.0.1\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\Program Files\nodejs\;C:\Users\Fatality\AppData\Local\Microsoft\WindowsApps;C:\Users\Fatality\AppData\Roaming\npm;C:\Users\Fatality\AppData\Local\GitHubDesktop\bin
9 verbose lifecycle newtondev-no-dev-fee-stratum-proxy@1.0.0~start: CWD: D:\mining\pr1\no-dev-fee-stratum-proxy-master
10 silly lifecycle newtondev-no-dev-fee-stratum-proxy@1.0.0~start: Args: [ '/d /s /c', 'node server.js' ]
11 silly lifecycle newtondev-no-dev-fee-stratum-proxy@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle newtondev-no-dev-fee-stratum-proxy@1.0.0~start: Failed to exec start script
13 verbose stack Error: newtondev-no-dev-fee-stratum-proxy@1.0.0 start: `node server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Fatality\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Fatality\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid newtondev-no-dev-fee-stratum-proxy@1.0.0
15 verbose cwd D:\mining\pr1\no-dev-fee-stratum-proxy-master
16 verbose Windows_NT 10.0.16299
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Fatality\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v9.8.0
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 1
22 error newtondev-no-dev-fee-stratum-proxy@1.0.0 start: `node server.js`
22 error Exit status 1
23 error Failed at the newtondev-no-dev-fee-stratum-proxy@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Can You help me ?

**Comment by NikiKaCode** [comment]
i write my data directly in js file and start working . 
zec mining.
thank you !
